@API_HostAddress = http://localhost:5131/api/performances


GET {{API_HostAddress}}?villages=kisharsany&villages=beremend&pageNumber=0&pageSize=60
Accept: application/json

###


POST {{API_HostAddress}}
Accept: application/json

###
