@API_HostAddress = http://localhost:5143/api

# Login
# @name postLogin
GET {{API_HostAddress}}/account/1951150A-1A00-4427-8910-FA8390FF8CBD
Content-Type: application/json; charset=utf-8

###
@token = {{postLogin.response.body.token}}


# Download program
POST {{API_HostAddress}}/program
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{token}}

###

# List program
GET {{API_HostAddress}}/program
Origin: http://localhost:8081/

###

GET http://192.168.0.31:5143/api/program?pageNumber=0&pageSize=3
Origin: http://localhost:8081

###

# List program
GET {{API_HostAddress}}/program?pageNumber=0&pageSize=20&searchText=cseh+tamás
Origin: http://localhost:8081

###

# List My program
GET {{API_HostAddress}}/program/my?pageNumber=0&pageSize=20
Authorization: Bearer {{token}}

###


# Select/deselect program
POST {{API_HostAddress}}/program/301eb61e-89b5-4d5b-a95a-7da5923a628e/select
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{token}}

###


GET https://ordogkatlan.hu/2024/az-ongyilkos?ajax=1
Accept: application/json
Origin: http://localhost:3000

###

